
[package]
name = "crobat"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Incoming crate"
readme = "README.md"
repository = "https://github.com/Its-Just-Nans/crates"

[[bin]]
name = "crobat"
path = "src/main.rs"

[dependencies]
