
[package]
name = "lugia"
version = "0.1.1"
description = "Incoming crate"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Its-Just-Nans/crates"

[[bin]]
name = "lugia"
path = "src/main.rs"

[dependencies]
